# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/main.py'],
    pathex=[],
    binaries=[],
    datas=[('src/static', 'static'), ('src/templates', 'templates')],
    hiddenimports=[
        'pydub',
        'librosa',
        'soundfile',
        'numpy',
        'whisper',
        'speech_recognition',
        'sklearn',
        'scipy',
        'numba',
        'llvmlite',
        'joblib',
        'threadpoolctl',
        'lazy_loader',
        'pooch',
        'soxr',
        'audioread',
        'decorator',
        'msgpack',
        'platformdirs',
        'torch',
        'torchaudio',
        'transformers',
        'tokenizers',
        'regex',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'packaging',
        'filelock',
        'typing_extensions',
        'sympy',
        'networkx',
        'jinja2',
        'markupsafe',
        'fsspec',
        'huggingface_hub',
        'safetensors',
        'pyyaml',
        'tqdm',
        'more_itertools'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='WhatsAppVoiceProcessor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
